config/routes.rb
Flash360::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :home
  resources :contacts
  resources :resume
  resources :users
  resources :sessions
  root :to => "home#index"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :subject, :message, :name, :remote_ip, :user_agent
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :password, :password_confirmation
  validates_uniqueness_of :email
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
  	redirect_to login_url, alert: "Not authorized" if current_user.nil?
	end
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authorize, only: [:index, :show, :destroy]

	def index
	  @contacts = Contact.all

	  respond_to do |format|
	   format.html # index.html.erb
	   format.json { render json: @contacts }
	  end

  end

  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conatact }
    end
  end

  def new
    @conatact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conatact }
    end
  end


  def create
  	
		@contact = Contact.new(params[:contact])
    @contact.remote_ip = request.remote_ip
    @contact.user_agent = request.headers["user-agent"]

    respond_to do |format|
      if @contact.save
        p_status = Prowler.notify "New Email: #{@contact.name} (#{@contact.email})", 
          "Subject:#{@contact.subject}\n #{contact_url(@contact)}"
        format.js
      else
        format.js
      end
    end
		#ContactMailer.email_success(params[:mail_form]).deliver
		#respond_to do |format|
		#flash.now[:notice] = "Your email was sent successfully!"
		#	format.js
		#end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController

	def index
		if !session[:resume_viewed] && !on_home_network?  
			prowler = Prowler.new(:delayed => true)
			p_status = Prowler.notify "Resume View", 
        		"#{request.remote_ip}, #{request.headers['user-agent']}"
      	session[:resume_viewed] = true
      	logger.info "Sending Push Notification: Resume View - #{request.remote_ip}, #{request.headers['user-agent']}"
     else
      	logger.info "Resume viewed suppressed, multiple views or on home network - #{request.remote_ip}, #{request.headers['user-agent']}"
     end
	end

	def new
		@question = "What is the sum of two plus two?"
	end

	def create
	  if params[:answer] == 4
	    session[:resume_allowed] = true
	    redirect_to resume_index_path
	  else
	    redirect_to new_resume_path
	  end
  	end

	def destroy
	    session[:resume_allowed] = nil
		redirect_to root_url
	end
	
	private

	def on_home_network?
			if request.remote_ip =~ /10\.10\.100/ ||
				 request.remote_ip == '127.0.0.1'
				return true
			else
				return false
			end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
	  user = User.find_by_email(params[:email])
	  if user && user.authenticate(params[:password])
	    session[:user_id] = user.id
	    redirect_to contacts_url, notice: "Logged in!"
	  else
	    flash.now.alert = "Email or password is invalid."
	    render :template => "sessions/new"
	  end
  end

	def destroy
			session[:user_id] = nil
			redirect_to root_url, notice: "Logged out!"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/experience_helper.rb
module ExperienceHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/contacts/_email_failed.html.erb
<div data-alert class=" radius alert-box alert">
	Sorry we could not send your email :( 
	<a href="" class="close"><i class="general foundicon-trash"></i></a>
</div>

app/views/contacts/_email_successful.html.erb
<div data-alert class=" radius alert-box success">
	Your email was sent successfully - :)
	<a href="" class="close"><i class="general foundicon-trash"></i></a>
</div>

app/views/contacts/_form.html.erb
 <% @contact = Contact.new %>
 <div class="row" >
   <fieldset>
    <legend>Contact</legend>
    <%= form_for @contact, :html => { :remote => true, 'data-abide' => true } do |f| %>
        <div class="row collapse">

          <div class="large-2 columns">
            <label class="inline">Your Name <small>required</small></label>
          </div>
          <div class="large-10 columns name_field">
            <input type="text" id="contact_name" name="contact[name]" placeholder="First Last" required >
            <small class="error">Name is required and must be at least one word.</small>
          </div>
        </div>

        <div class="row collapse">
          <div class="large-2 columns email_field">
            <label class="inline"> Your Email <small>required</small></label>
          </div>
          <div class="large-10 columns">
            <input type="email" id="contact_email" name="contact[email]" placeholder="you@yourwebsite.com" required>
            <small class="error">A valid email address is required.</small>
          </div>      
        </div>

        <div class="row collapse">
          <div class="large-2 columns ">
            <label class="inline"> Email Subject <small>required</small></label>
          </div>
          <div class="large-10 columns">
            <input type="text" id="contact_subject" name="contact[subject]" placeholder="" required>
            <small class="error">Email subject is required.</small>
          </div>      
        </div>
        
        <label>What can I help you with? <small>required</small></label>
        <textarea rows="4" id="contact_message" name="contact[message]" required></textarea>
        <small class="error">You forgot the message body.</small>
        <button type="submit" class="radius button">Submit</button>
      
      <% end %>
    </fieldset>
    <a class="close-reveal-modal"><i class="general foundicon-remove"></i></a>
</div>         

app/views/contacts/create.js.erb
$('#contactModal').foundation('reveal', 'close');
$('#flash').html('<%= escape_javascript( render :partial => "contacts/email_successful").html_safe %>');
$('#contactModal').html('<%= escape_javascript(render :template => "contacts/new") %>');

app/views/contacts/index.html.erb
<% content_for :title do %>
  Inbox
<% end %>
<div class="row">
  <div class="12-large columns">
    <table>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Subject</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.subject %></td>
        <td><%= link_to 'Show', contact , class: "small radius button" %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' }, class: "small radius button" %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>

app/views/contacts/new.html.erb
<%= render 'form' %>

app/views/contacts/show.html.erb
<% content_for :title do %>
  Message - <%= @contact.subject %>
<% end %>
<div class="row">
  <div class="large-12 columns">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @contact.name %>
</p>

<p>
  <b>Email:</b>
  <%= @contact.email %>
</p>

<p>
  <b>Subject:</b>
  <%= @contact.subject %>
</p>

<p>
  <b>Message:</b><br/>
  <%= @contact.message %>
</p>


<%= link_to '<i class="general foundicon-left-arrow"></i>'.html_safe, contacts_path, class: "small radius button" %>
<%= link_to '<i class="general foundicon-mail"></i>'.html_safe, "mailto:#{@contact.email}?subject=Re:#{@contact.subject}", class: "small radius button" %>

<%= link_to '<i class="general foundicon-checkmark"></i>'.html_safe, contacts_path, class: "small radius button" %>
<%= link_to '<i class="general foundicon-trash"></i>'.html_safe, contacts_path, class: "small radius button" %>

</div>
</div>

app/views/footer/show.html.erb
<!-- Footer -->
<div id="footer" style="background-color: #222; border-top: 4px solid #666;">
  
  <footer class="row">
    <div class="large-12 columns">
      <div class="row" style="margin-top:25px;">
        <div class="large-8 columns hide-for-small">
          <p style="color:#3e94d1; text-transform:uppercase; letter-spacing:1.5px">&copy; 2013 Flash360 Consulting, LLC.</p>
        </div>
        <div class="large-4 columns">
            <ul class="inline-list right" style="font-size: 1.5em;">
<!--             <% if current_user %>
              <li><a href="<%= logout_path %>"><i class="general foundicon-lock"></i></a></li>
            <% else %>
              <li><a href="<%= login_path %>" style="color:#e9e9e9;"><i class="general foundicon-unlock"></i></a></li>
            <% end %> -->
            <li><a href="http://www.github.com/jeffhigham"><i class="social foundicon-github"></i></a></li>
            <li><a href="http://www.facebook.com/flash360tech"><i class="social foundicon-facebook"></i></a></li>
            <li><a href="http://www.twitter.com/flash360tech"><i class="social foundicon-twitter"></i></a></li>
            <li><a href="http://www.linkedin.com/in/jeffhigham"><i class="social foundicon-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
    </div> 
  </footer>

</div>
<!-- /Footer -->

app/views/google/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42880626-1', 'flash360.pro');
  ga('send', 'pageview');

</script>

app/views/home/index.html.erb
<!-- First Band (Slider) -->

  <div class="row">
    <div class="large-12 columns ">
    <ul data-orbit >
      <li><a href="#"><img class="image_rounded" src="/webdev-slider.png" alt="Website Development - PHP, Ruby on Rails, JQuery, HTML5, CSS"/></a></li>
      <li><a href="#"><img class="image_rounded" src="/cloud-slider.png" alt="Cloud Computing - AWS, Heroku, Linode, RackSpace"/></a></li>
      <li><a href="#"><img class="image_rounded" src="/linuxadmin-slider.png" alt="Server Administration - Linux, Solaris, VMware, Web Servers, Database Servers"/></a></li>
    </ul>
    </div>
  </div>
   <br/> 
<div class="row ">
  <div class="large-6 columns ">
    <h4><img  style="height:60px" src="/Ruby_on_Rails-logo.png"/> Ruby on Rails</h4><hr/>
    <p style="text-align:justify">Developing websites using the <a href="http://en.wikipedia.org/wiki/Ruby_on_Rails">Ruby on Rails</a> framework is very fulfilling for me as a developer, and can be cost-effective for you as my client.  With many of the architecture decisions (MVC, CoC, DRY, REST) in place before the first line of code is written, Rails hits the ground running.  Rails can make it possible to put together an advanced, database-driven prototype in a matter of hours and a mature product in a matter of weeks.  At the heart of a Rails project is the <a href="https://www.ruby-lang.org/en/">Ruby programming language</a>.  It is highly intuitive, flexible, and robust and can make quick work of the most complicated coding tasks.  Will your hosting provider support Rails websites?  It has been my experience that most major hosting providers do. If your provider does not, I can help you find one that does.</p> 
  </div>
  <div class="large-6 columns ">
    <h4><img style="height:60px" src="/php-logo.jpeg"/> PHP</h4><hr/><p style="text-align:justify"><a href="http://php.net/">PHP</a> was my first introduction website development in the early 2000s.  Today, PHP is one of the most popular programming languages in used for web development and one I have spent a great deal of time using. <a href="http://en.wikipedia.org/wiki/CakePHP">CakePHP</a> is a MVC framework that adds Rails-like functionality to PHP.   This can be a great choice to save some time writing a custom, from the ground up application. Many of my clients prefer to use the <a href="http://en.wikipedia.org/wiki/WordPress">Wordpress content management system</a> for their website.  Although this is written in PHP, it is designed primarily to be hands-off the code offering pre-built themes, and plugins as an alternative.  Under the hood, Wordpress can be customized endlessly.  If you need a custom plugin, theme, or just a few tweaks I can take care of those for you.</p>
  </div>
</div><br/>
<div class="row">
  <div class="large-12 columns">
    <h4><img style="height:60px" src="/cloud_icon_1.png"/> Cloud Hosting | Systems Administration</h4><hr/>
    <p style="text-align:justify">I would love to spend all of my time developing your website and making it do awesome things for you (believe me I really would), but that will all go to waste unless the world can see it.  This is where I get to use my secret arsenal of weaponry. As it turns out, working in the world of tech for 12 years one can gain a broad skill set.  Unlike many developers, I really do know my way around the technologies that make the Internet go. I can transfer your domain name and email accounts, build a cloud-based secure Linux hosting environment, scale your site to meet demand, and much more.  I've been on the other side of the fence with all of these technologies and know how they work behind the scenes at your hosting provider.
    </p>
  </div>
</div><br/>

<!-- Contact Panel -->
<div class="row">
    <div class="large-12 columns">
    
      <div class="radius panel">
        <h4>Let's Talk!</h4>
            
        <div class="row">
          <div class="large-9 columns">
            <p>I would love to help you with your next project.  Drop me a line and let me know what you need.</p>
          </div>
          <div class="large-3 columns">
            <a href="#" data-reveal-id="contactModal" class="radius button right">Get in touch</a>
          </div>
        </div>
      </div>
      
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title>Flash360 Consulting, LLC - <%= content_for?(:title) ? yield(:title) : " Website Development, Cloud Computing, Systems Engineering" %></title>
    <meta name="description=" content="Flash360 Consulting - Website development in PHP, Ruby on Rails, HTML5, JQuery, CSS, and more. Cloud Computing using Amazon Web Services (AWS), Linode, RackSpace, and Heroku. Server Administration expertise in Linux, Solaris, VMWare, webservers, and database servers. ">

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
<!-- layout -->
<div id="layout">
<!-- Navigation -->
  <nav class="top-bar">
    <ul class="title-area">
      <!-- Title Area -->
      <li class="name">
        <h1>
          <a href="<%= home_index_path %>">
            <img class="logo" alt="Flash360 Logo" src="/f360-logo.png" />
          </a>
        </h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
    </ul>
    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li class="divider"></li>
        <li><a href="<%= resume_index_path %>">Experience</a></li>
        <li class="divider"></li>
        <li><a href="#" data-reveal-id="contactModal">Contact</i> </a></li>
        <% if current_user %>
          <li class="divider"></li>
          <li><a href="<%= contacts_path %>" style="color:#3e94d1"><i class="general foundicon-inbox"></i></a></li>
        <% end %>
      </ul>
    </section>
  </nav>
  
  <!-- End Header and Nav -->

  <!-- Flash Notifications -->
  <div class="row">
    <div class="12-large columns" id="flash"></div>
  </div>

  <!-- Content -->

  <%= yield %>

  <!-- sticky footer -->
  <div id="layout_footer"></div>
  <!-- /sticky footer -->

  </div> <!-- /layout -->

  <%= render :template => "footer/show" %>
  
  <!-- modal -->
  <div id="contactModal" class="reveal-modal">
  <%= render :partial => "contacts/form" %>
  </div>
  <%= javascript_include_tag "application" %>
  <%= render :partial => "google/analytics" %>
  </body>
</html>

app/views/notifications/email_success.text.erb
<%= @mail_form[:body] %>

~ <%= "#{@mail_form[:name]} #{@mail_form[:email]}" %>

app/views/resume/_education.html.erb
<h5 class="subheader">University of Phoenix</h5>
<h6 class="subheader">Bachelor of Science, Information Technology, 2005-2007</h6>
<hr/>

<h5 class="subheader">University of Colorado at Denver</h5>
<h6 class="subheader">Computer Science, 2000-2004</h6>

app/views/resume/_expertise.html.erb
<%
software_experience = [ 
'Ruby',
'PHP',
'Perl',
'C++',
'JQuery',
'CoffeeScript',
'CSS',
'SCSS',
'Agile Web Development',
'Mobile Application Development',
'PhoneGap',
'Node.js',
'RESTful WebServices',
'MVC Development Frameworks',
'Subversion',
'Git',
'Mercurial',
'Photoshop',
'Illustrator',
'Foundation 4',
'Twitter Bootstrap',
'Ruby on Rails',
'CakePHP',
'Sails.js',
'Wordpress'
]

systems_experience = [ 
'Linux',
'Solaris',
'MySQL',
'MongoDB',
'Apache',
'Nginx',
'Weblogic / SOA',
'Tomcat',
'Systems Architecture',
'Virtualization',
'Shell Scripting',
'DTrace',
'High Availability',
'Clustering',
'Oracle RAC',
'Linux HA',
'MemCached',
'Cloud Computing',
'Amazon Web Services (AWS)',
'Heroku',
'Linode'
]
%>
<h4 class="subheader">Software</h4>
<% software_experience.each do |e| %>
<span class="radius secondary label"><%= e %></span>
<% end %>
<p/>
<h4 class="subheader">Systems</h4>
<% systems_experience.each do |e| %>
<span class="radius secondary label"><%= e %></span>
<% end %>
<p/>

app/views/resume/_software_experience.html.erb
		<h5 class="subheader"><a href="http://www.tangosquared.com" data-dropdown="biggergains" data-options="is_hover:true">Bigger Gains International</a></h5>
		<h6 class="subheader">Ruby on Rails Developer</h6>
			<P>Bigger Gains is a leadership training, coaching, and consulting firm and creator of a unique personality profile test named "The Raw Personality Indicator". I am working with them to develop and launch a new site in Ruby on Rails targeted at the mobile market.  Aided by the Zurb Foundation 4 framework, I created a simple and responsive layout that works great on all screen sizes.  The site is in the final stages and will soon be live at www.rawpersonality.com Fall 2013.</P><hr/>
		<ul id="biggergains" class="f-dropdown small " data-dropdown-content>
			  <a href="http://www.biggergains.com" target="_blank"><img src="/biggergains.png"/></a>
		</ul>
		<h5 class="subheader"><a href="http://www.tangosquared.com" data-dropdown="tangosquared" data-options="is_hover:true">TangoSquared</a></h5>
		<h6 class="subheader">PHP Developer, Cloud Hosting, Technology Consultant</h6>
			<P>My involvement with TangoSquared has been a great experience. They do amazing design work and are making a name for themselves as a boutique design and development firm.  My experience as a developer and systems engineer brought us into a working relationship.  I manage their cloud hosting platform and sling PHP code for custom WordPress plugins and back-end functionality.</P><hr/>
		<ul id="tangosquared" class="f-dropdown small " data-dropdown-content>
			  <a href="http://www.tangosquared.com" target="_blank"><img src="/tango.png"/></a>
		</ul>

		<h5 class="subheader"><a href="http://freedrugcardsite.com" data-dropdown="freedrugcardsite" data-options="is_hover:true">PharmaStrategies, LLC</a></h5>
		<h6 class="subheader">Ruby on Rails Developer</h6>
			<P>PharmaStrategies provides a discount pharmacy card for individuals without insurance. Their site runs on Ruby on Rails.  My work for them includes a RESTful API for drug and pharmacy lookup, i18n localization into Spanish, and Rails upgrades.</P><hr/>
		<ul id="freedrugcardsite" class="f-dropdown small " data-dropdown-content>
			  <a href="http://freedrugcardsite.com" target="_blank"><img src="/rxcard.png"/></a>
		</ul>

		<h5 class="subheader"><a href="http://www.nlgshow.com" data-dropdown="nlgshow" data-options="is_hover:true">National Lawn &amp; Garden Show</a></h5>
		<h6 class="subheader">Tcl, PHP, Perl Developer / Systems Engineering</h6>
			<P>NLGS puts on a large networking event every June for Buyers, Vendors, and Manufacturing Representatives in the Lawn & Garden and Pet Products industries.  The event requires complicated scheduling for 10-minute meetings between Buyers and Vendors based on pre-defined preference selections. These meetings rotate all day every 10 minutes with the whole event lasting 3-4 days.  The scheduling platform is a mix of PHP, Perl, SQL, and TCL.  I help maintain this code and provide on-site support during the event each year.</P><hr/>
		<ul id="nlgshow" class="f-dropdown small " data-dropdown-content>
			  <a href="http://www.nlgshow.com" target="_blank"><img src="/nlgshow.png"/></a>
		</ul>

		<h5 class="subheader"><a href="http://www.cyandia.com" data-dropdown="cyandia" data-options="is_hover:true">Cyandia</a></h5>
		<h6 class="subheader">PHP Developer / Cloud Engineer</h6>
			<P>Cyandia.me provides a rich mobile experience centered on entertainment with a strong social component. I provided back-end PHP development and managed their AWS environment.</P><hr/>
		<ul id="cyandia" class="f-dropdown small " data-dropdown-content>
			  <a href="http://www.cyandia.com" target="_blank"><img src="/cyandia.png"/></a>
		</ul>

		<h5 class="subheader"><a href="http://www.zmanda.com" data-dropdown="zmanda" data-options="is_hover:true">Zmanda, Inc</a></h5>
		<h6 class="subheader">Software Developer / Systems Engineering</h6>
			<P>Zmanda provides Enterprise, MySQL, and Cloud Backups solutions and has now joined forces with Carbonite. As a backup solutions provider, they have very complex infrastructure needs. They have unique challenges providing backup solutions on heterogeneous platforms.  My roles was to help engineer and manage a virtual environment for product development and testing. With the aid of scripting and custom software I was able to automate much of the build up, test, and tear down in these environments.</P><hr/>
		<ul id="zmanda" class="f-dropdown small " data-dropdown-content>
			  <a href="http://www.zmanda.com" target="_blank"><img src="/zmanda.png"/></a>
		</ul>

		<h5 class="subheader"><a href="http://web.archive.org/web/20061206031646/http://www.ninesystems.com/"  data-dropdown="ninesystems" data-options="is_hover:true">NineSystems (Akamai)</a></h5>
		<h6 class="subheader">PHP, Perl Software Developer</h6>
			<P>At NineSystems (now owned by Akamai), I was part of a development team supporting their in-house streaming platform: StreamOS. This was written in PHP, Perl, and C although most of my time was in PHP, and Perl. I developed a stream testing platform, server monitoring platform, and change management system in addition to supporting StreamOS directly.</P><hr/>
		<ul id="ninesystems" class="f-dropdown small " data-dropdown-content>
			  <a href="http://web.archive.org/web/20061206031646/http://www.ninesystems.com/" target="_blank"><img src="/ninesystems.png"/></a>
		</ul>

		<h5 class="subheader"><a href="http://www.monsonboards.com"  data-dropdown="monsonboards" data-options="is_hover:true">Monson Boards</a></h5>
		<h6 class="subheader">PHP Developer</h6>
			<P>Monson Boards began as an OEM snowboard manufacturer and has since expanded into other markets.  I worked for them developing a custom order tracking systems for their OEM customers. This was written from the ground up with PHP/MySQL.</P>
		<ul id="monsonboards" class="f-dropdown small " data-dropdown-content>
			  <a href="http://www.monsonboards.com" target="_blank"><img src="/monsonboards.png"/></a>
		</ul>

app/views/resume/index.html.erb
<% content_for :title do %>
  Experience, Expertise, Education
<% end %>
<!-- Breadcrums -->
<div class="row">
  <div class="12-large columns">
    <ul class="breadcrumbs">
      <li><%= link_to 'Home', home_index_path %></li>
      <li class="current"><a href="#">Experience</a></li>
    </ul>
  </div>
</div>

<div class="row hide-for-small">
  <div class="large-3 columns" >
    <img class="image_rounded" src="/avatar.jpg"/>
  </div>
  <div class="large-9 columns">
    <div class="radius panel">
      <h3>About Flash360 Consulting</h3>
      <blockquote>I love high-performance operating systems, finding solutions to complicated technical problems, and writing good code.  I have a deep appreciation for quality design work and user experience, especially the difficulty in accomplishing both.  I slung my first line of Perl code in 1998, authored my first PHP website in 2000, and haven't looked back since. Technology has covered a lot of ground over the past 13+ years and I have enjoyed being along for the ride. We now have amazing tools at our disposal - Ruby on Rails, JQuery, Node.js, PhoneGap, Cloud-based web hosting, RESTful APIs, and too many more to mention.   My goal is to continue to innovate with the industry and hopefully help you do the same. So, please take a moment to see what I've been up to and let me know how I can help.
      </blockquote>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <h3>Experience</h3>
    <%= render "work_history" %>
    <h3>Expertise</h3>
    <%= render "expertise" %>
    <h3>Education</h3>
    <%= render "education" %>
  </div>
</div>

app/views/resume/new.html.erb
<div class="row">
	<div class="large-12 columns">
		<%= form_tag resume_path do %>
		  <div class="field">
		          <%= label_tag :question %><br />
		          <%= text_field_tag :question %>
		  </div>
		  <%= submit_tag "Answer", class: "small radius button" %>
		<% end %>
	</div>
</div>